// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityReference } from "./EntityReference";
import type { HnItem } from "./HnItem";

export type EntityItemWithHighlights = { item: HnItem, highlights: Array<EntityReference>, };