// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResult } from "./webapp/src/types/tools/ToolResult";

export type ExecuteToolResponse = { result: ToolResult, };