// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionStats } from "./ExtractionStats";

export type ExtractionStatusResponse = { extraction_stats: ExtractionStats, };