// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolSchema } from "./webapp/src/types/tools/ToolSchema";

export type GetToolSchemaResponse = { schema: ToolSchema, };