// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolDescriptor } from "./webapp/src/types/tools/ToolDescriptor";

export type GetToolsResponse = { tools: Array<ToolDescriptor>, };