// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchEntitiesRequest = { q: string | null, entity_type: string | null, page: number | null, limit: number | null, };