// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simplified Entity for API responses
 */
export type Entity = { id: bigint, entity_value: string, entity_type: string, confidence: number, created_at: string, };