// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoreRange } from "./ScoreRange";
import type { TimeRange } from "./TimeRange";

/**
 * Parameters for filtering HN items
 */
export type FilterItemsParams = { 
/**
 * Filter by score range (min and max)
 */
score_range: ScoreRange | null, 
/**
 * Filter by time range
 */
time_range: TimeRange | null, 
/**
 * Filter by comment count range
 */
comment_count_range: ScoreRange | null, 
/**
 * Filter by specific authors
 */
authors: Array<string> | null, 
/**
 * Maximum number of results to return
 */
limit: number, };