// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simplified HN Item for API responses
 */
export type HnItem = { id: bigint, title: string | null, by: string | null, score: number | null, item_type: string, time: string, text: string | null, url: string | null, descendants: number | null, };