// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameter types for tool arguments
 */
export type ParameterType = "String" | "Integer" | "Float" | "Boolean" | "Array" | "Object" | "Date";