// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";
import type { EntityRelation } from "./EntityRelation";

/**
 * Entity relation with full entity details
 */
export type RelationWithEntities = { relation: EntityRelation, subject_entity: Entity, object_entity: Entity, source_item_count: number, };