// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityWithStats } from "./EntityWithStats";
import type { SearchEntitiesParams } from "./SearchEntitiesParams";

/**
 * Response from searching entities
 */
export type SearchEntitiesResponse = { entities: Array<EntityWithStats>, total_count: bigint, query_applied: SearchEntitiesParams, query_time_ms: bigint, };