// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolSchemaExample } from "./ToolSchemaExample";

/**
 * Tool schema information
 */
export type ToolSchema = { name: string, parameter_schema: any, response_schema: any, examples: Array<ToolSchemaExample>, };