// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool usage example
 */
export type ToolExample = { description: string, input: any, expected_output: any, use_case: string, };