// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation warning for tool parameters
 */
export type ValidationWarning = { field: string, warning_type: string, message: string, suggestion: string | null, };