// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepResult } from "./StepResult";
import type { StepStatus } from "./StepStatus";
import type { StepType } from "./StepType";
import type { ToolExecution } from "./ToolExecution";

export type ConversationStep = { step_id: number, step_type: StepType, llm_request: string | null, llm_response: string | null, tool_calls: Array<ToolExecution>, results: StepResult | null, status: StepStatus, created_at: string, };