// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationContext } from "./ConversationContext";
import type { ConversationState } from "./ConversationState";
import type { ConversationStep } from "./ConversationStep";

export type Conversation = { id: string, user_query: string, state: ConversationState, steps: Array<ConversationStep>, context: ConversationContext, created_at: string, updated_at: string, };