// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSummary } from "./DataSummary";
import type { ToolDescriptor } from "./ToolDescriptor";
import type { ToolExecution } from "./ToolExecution";
import type { UserPreferences } from "./UserPreferences";

export type ConversationContext = { available_tools: Array<ToolDescriptor>, data_summary: DataSummary, user_preferences: UserPreferences, execution_history: Array<ToolExecution>, intermediate_results: Record<string, unknown>, };