// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataSummary = { entity_count_by_type: { [key: string]: bigint }, relation_count_by_type: { [key: string]: bigint }, item_count_by_timeframe: { [key: string]: bigint }, data_freshness: string, };