// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolExecution = { tool_name: string, parameters: unknown, result: unknown | null, error: string | null, execution_time_ms: bigint | null, };