// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferences = { max_conversation_steps: number | null, preferred_response_format: string | null, timeout_seconds: bigint | null, };