// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadStats = { total_items: number, total_users: number, last_download_time: string | null, items_downloaded_today: number, download_errors: number, is_downloading: boolean, };