// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityRelation = { id: bigint, subject_entity_id: bigint, object_entity_id: bigint, relation_type: string, confidence: number | null, created_at: string, };