// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Entity = { id: bigint, item_id: bigint, entity_type: string, entity_value: string, original_text: string, start_offset: bigint, end_offset: bigint, confidence: number | null, created_at: string, };