// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";

/**
 * Entity with additional statistics
 */
export type EntityWithStats = { entity: Entity, mentions_count: number, first_mentioned: string | null, last_mentioned: string | null, related_entities_count: number, };