// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolArguments } from "./webapp/src/types/tools/ToolArguments";

export type ExecuteToolRequestNew = { tool_name: string, arguments: ToolArguments, };