// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractionStats = { total_entities: bigint, entities_by_type: Record<string, number>, total_items_processed: bigint, items_remaining: bigint, is_extracting: boolean, last_extraction_time: string | null, };