// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetRelationsRequest = { page: number | null, limit: number | null, entity_id: bigint | null, relation_type: string | null, };