// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

import type { ModelInfo } from './ModelInfo';

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo";

export type ModelsResponse = { models: Array<ModelInfo>, };