// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterType } from "./ParameterType";
import type { ValidationRule } from "./ValidationRule";

/**
 * Tool parameter definition
 */
export type Parameter = { name: string, param_type: ParameterType, description: string, required: boolean, default_value: unknown, validation: ValidationRule | null, };