// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool schema example
 */
export type ToolSchemaExample = { name: string, description: string, parameters: any, expected_response: any, };