// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool execution result
 */
export type ToolResult = { success: boolean, data: any, message: string | null, execution_time_ms: bigint, errors: Array<string>, warnings: Array<string>, };