// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCategory } from "./ToolCategory";
import type { ToolConstraints } from "./ToolConstraints";
import type { ToolExample } from "./ToolExample";
import type { ToolParameters } from "./ToolParameters";

/**
 * Comprehensive tool descriptor
 */
export type ToolDescriptor = { name: string, description: string, category: ToolCategory, version: string, parameters: ToolParameters, examples: Array<ToolExample>, constraints: ToolConstraints, tags: Array<string>, };