// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationResult } from "./webapp/src/types/tools/ValidationResult";

export type ValidateToolParamsResponse = { validation_result: ValidationResult, };