// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for exploring entity relationships
 */
export type ExploreRelationsParams = { 
/**
 * Filter by specific relation type (founded, acquired, works_at, etc.)
 */
relation_type: string | null, 
/**
 * Focus on relations for specific entity ID
 */
entity_id: bigint | null, 
/**
 * Focus on relations involving specific entity name
 */
entity_name: string | null, 
/**
 * Minimum confidence threshold (0.0-1.0)
 */
min_confidence: number | null, 
/**
 * Maximum number of results to return
 */
limit: number, };