// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExploreRelationsParams } from "./ExploreRelationsParams";
import type { RelationWithEntities } from "./RelationWithEntities";

/**
 * Response from exploring entity relationships
 */
export type ExploreRelationsResponse = { relations: Array<RelationWithEntities>, total_count: bigint, query_applied: ExploreRelationsParams, query_time_ms: bigint, };