// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterItemsParams } from "./FilterItemsParams";
import type { HnItem } from "../HnItem";

/**
 * Response from filtering HN items
 */
export type FilterItemsResponse = { items: Array<HnItem>, total_count: bigint, filters_applied: FilterItemsParams, query_time_ms: bigint, };