// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query context for tool execution
 */
export type QueryContext = { user_id: string | null, session_id: string | null, request_id: string | null, metadata: Record<string, unknown>, };