// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

/**
 * Filters that were applied to the search
 */
export type SearchItemsFilters = { query: string, author: string | null, item_type: string | null, min_score: number | null, time_range: TimeRange | null, limit: number, };