// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchItemsParams = { query: string, author: string | null, item_type: string | null, min_score: number | null, limit: number | null, };