// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HnItem } from "../../../../bindings/HnItem";

export type SearchItemsResponse = { items: Array<HnItem>, total_count: bigint, query_time_ms: bigint, };