// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

/**
 * Parameters for searching HN items
 */
export type SearchItemsParams = { 
/**
 * Search keywords or phrases to find in item titles and text
 */
query: string, 
/**
 * Filter by specific author username
 */
author: string | null, 
/**
 * Filter by item type (story, comment, job, poll)
 */
item_type: string | null, 
/**
 * Minimum score threshold for items
 */
min_score: number | null, 
/**
 * Date range for filtering items
 */
time_range: TimeRange | null, 
/**
 * Maximum number of results to return (1-1000)
 */
limit: number, };