// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HnItem } from "../HnItem";
import type { SearchItemsFilters } from "./SearchItemsFilters";

/**
 * Response from searching HN items
 */
export type SearchItemsResponse = { items: Array<HnItem>, total_count: bigint, query_time_ms: bigint, filters_applied: SearchItemsFilters, };