// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for searching entities
 */
export type SearchEntitiesParams = { 
/**
 * Entity name or partial name to search for
 */
query: string | null, 
/**
 * Filter by entity type (person, company, technology, etc.)
 */
entity_type: string | null, 
/**
 * Minimum confidence threshold (0.0-1.0)
 */
min_confidence: number | null, 
/**
 * Minimum number of mentions
 */
min_mentions: number | null, 
/**
 * Maximum number of results to return
 */
limit: number, };