// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool constraints and limitations
 */
export type ToolConstraints = { max_execution_time_ms: bigint | null, max_result_size: number | null, rate_limit_per_minute: number | null, requires_authentication: boolean, };