// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameter } from "./Parameter";

/**
 * Tool parameter schema
 */
export type ToolParameters = { parameters: Array<Parameter>, json_schema: Record<string, unknown>, };