// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool performance metrics
 */
export type ToolMetrics = { total_executions: bigint, successful_executions: bigint, failed_executions: bigint, average_execution_time_ms: number, last_execution: string | null, };