// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Validation rules for tool parameters
 */
export type ValidationRule = { min_value: number | null, max_value: number | null, min_length: number | null, max_length: number | null, pattern: string | null, allowed_values: Array<string> | null, };