// This file is auto-generated by `cargo run --bin export_types`
// Do not edit manually.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValidationError } from "./ValidationError";
import type { ValidationWarning } from "./ValidationWarning";

/**
 * Validation result for tool parameters
 */
export type ValidationResult = { is_valid: boolean, errors: Array<ValidationError>, warnings: Array<ValidationWarning>, };