name: Webapp CI

on:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/workflows/webapp-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'webapp/**'
      - '.github/workflows/webapp-ci.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    
    steps:
    - uses: actions/checkout@v4
      with:
        # For pull requests, checkout the head commit of the PR branch
        # This ensures we test the actual code in the PR, not a merge commit
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: webapp/pnpm-lock.yaml
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Type check
      run: pnpm exec tsc -b --noEmit
    
    - name: Run ESLint
      run: pnpm lint
    
    - name: Build
      run: pnpm build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp-dist
        path: webapp/dist/
        retention-days: 7